spring.application.name=music

spotify.client-id=${SPOTIFY_CLIENT_ID}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET}

youtube.client-id={{YT_CLIENT_ID}}
youtube.client-secret={{YT_CLIENT_SECRET}}
youtube.redirect-urls={{YT_REDIRECT_URL}}